### PR TITLE
Fix obs-build workflow

### PR DESCRIPTION
**Pull request by jcronenberg**
## Problem and Solution

OBS automatic build submission was missing removing and adding the new `.obscpio` file and also I need to be more 'agile' with the account so I wanted to store the user in a secret as well instead of hard coding it.

### CODE REVIEW

**Comment by jcronenberg** [comment]
Note: Testing is currently very limited, because OBS account creation isn't working. I'll mark it as ready for review once my bot account is able to log in and I'm able to test the workflow.

**Comment by jcronenberg** [comment]
Alright bot account is working and test run was successful https://github.com/jcronenberg/agama/actions/runs/7184776513/job/19566631944

**Review by clemix-fpv — APPROVED** [review]
:partying_face:

**Review by clemix-fpv — APPROVED** [review]
LGTM

**Review by cfconrad — APPROVED** [review]
LGTM

**Pull request merged**
